language: R
cache: packages
sudo: true

env:
  global:
  - _R_CHECK_FORCE_SUGGESTS_=false

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libudunits2-dev

matrix:
  include:
  - r: devel
  - r: release
  - r: oldrel
